*&---------------------------------------------------------------------*
*& Include          ZBRFI0060_TOP
*&---------------------------------------------------------------------*

*&---------------------------------------------------------------------*
*& TABLE, TYPE, STRUCTURE 선언.
*&---------------------------------------------------------------------*
DATA: OK_CODE    TYPE SY-UCOMM,
      GV_DYNNR   TYPE SY-DYNNR,
      GS_VARIANT TYPE DISVARIANT,
      GV_MODE    TYPE I VALUE 1.

TABLES: ZTBFI0030, ZTBFI0031, ZVBFI0030,
        ZSBFI0030_BP, ZSBFI0030_POP1, ZSBFI0030_POP2.

* ALV1 DATA TYPE
DATA: GS_DISPLAY1 TYPE ZSBFI0030_ALV1,
      GT_DISPLAY1 LIKE TABLE OF GS_DISPLAY1.

* ALV1 WA & ITAB
DATA: GO_CUST1 TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GO_ALV1  TYPE REF TO CL_GUI_ALV_GRID,
      GS_LAYO1 TYPE LVC_S_LAYO,
      GT_SORT1 TYPE LVC_T_SORT,
      GS_SORT1 TYPE LVC_S_SORT,
      GT_FCAT1 TYPE LVC_T_FCAT,
      GS_FCAT1 TYPE LVC_S_FCAT.

* ALV1 SELECTED ROW ITAB & WA.
DATA: GT_ROW1 TYPE LVC_T_ROID,
      GS_ROW1 TYPE LVC_S_ROID.

* ALV2 DATA TYPE
DATA: GS_DISPLAY2 TYPE ZSBFI0030_ALV2,
      GT_DISPLAY2 LIKE TABLE OF GS_DISPLAY2.

* ALV2 WA & ITAB
DATA: GO_CUST2 TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GO_ALV2  TYPE REF TO CL_GUI_ALV_GRID,
      GS_LAYO2 TYPE LVC_S_LAYO,
      GT_SORT2 TYPE LVC_T_SORT,
      GS_SORT2 TYPE LVC_S_SORT,
      GT_FCAT2 TYPE LVC_T_FCAT,
      GS_FCAT2 TYPE LVC_S_FCAT.

* ALV2 SELECTED ROW ITAB & WA.
DATA: GT_ROW2 TYPE LVC_T_ROID,
      GS_ROW2 TYPE LVC_S_ROID.

* ALV3 DATA TYPE
DATA: GS_DISPLAY3 TYPE ZSBFI0030_ALV3,
      GT_DISPLAY3 LIKE TABLE OF GS_DISPLAY3.

* ALV3 WA & ITAB
DATA: GO_CUST3 TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GO_ALV3  TYPE REF TO CL_GUI_ALV_GRID,
      GS_LAYO3 TYPE LVC_S_LAYO,
      GT_SORT3 TYPE LVC_T_SORT,
      GS_SORT3 TYPE LVC_S_SORT,
      GT_FCAT3 TYPE LVC_T_FCAT,
      GS_FCAT3 TYPE LVC_S_FCAT.
